language: node_js
node_js:
  - 16 # uses version 12
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
script:
  - npm run build # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: carrectly-nextjs
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: GmJ104h7CA0GtfaLDUfjyjXku+FRGlHzjFUNYKAsHnBMb3U8ryHBbpJnfb5ep92oN1YSBojehl+rOj9MrpFozGmpgfNGo+3KN/CzYYPhd7oz3WcRqsKN0TJGvtA1QoYMO5ui4jqnLJCNtqQeWNntt21fYASlDIQYhi1oYUHRPQf4zkZyL+sk6enFw+/YatSxg1CkuWzmhEHJzAsGOTSoI4dtej2oM1+K1AltxCHdkf+K6TRjxvCj/xUVOIDvE9FLF4vlLeMsm+c22w/bRw3oDLDimlcRmeaumzuiP+yZBgKG6tY2h26E8rNbrsr4pzZW0X+IuvbTfO30ezF3y2rGrTh3y0nLmNb/KuSoQ6Am9a4SHIJ7jAdj7gPqCN3IB6Rz2jJZup2pOZv4LLdiXh5gOdQGX8yA0xWg/aqaTBMG7BCyYrkrMAgs6DdTOwHDeX2AMN8E0RcToc18mSzpTzbVHVp6ypHgu92+e6cs59t0jSJQ1W51r7GgqOyID1QI6pjOJgyFjF5TfTEGZ3ACA8f3UZn+gl+sofefDaxuFFe3//H8lSDxzhgoST2DwtQX/QL1Pd4EP5/iAo22CVZ/wUAoSvGYl/eJBFoK/KMz/EExCGb1km5kPnGMam5xCNgKUDxxIIUl3CmlipbP9Ora707yi5MSlLbL6P/X0AG72u0vrW8=
