apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrectlyweb
  namespace: default
spec:
  selector:
    matchLabels:
      app: carrectlyweb
  replicas: 3
  template:
    metadata:
      labels:
         app: carrectlyweb
    spec:
      containers:
        - name: carrectlyweb
          image: "<imageTag>"

---
    apiVersion: v1
    kind: Service
    metadata:
      name: carrectlyweb-service
      labels:
        app: carrectlyweb
    spec:
       ports:
        - name: carrectlyweb
          port: 3000
          targetPort: 3000
       selector:
        app: carrectlyweb
